### ISSUE TITLE
Feature request: hide selected images and display a message when all have been selected

### ISSUE THREAD

**Issue by romaincazier** [Toutouwai/InputfieldSelectImages#8]
Hi @Toutouwai,

This is more of a feature request than a bug: I’m using your module to allow editors to select artworks from referenced artists in an exhibition page.

When there are several artists it can end up with quite a few images to select from. I wondered if it would make sense to hide the selected image (instead of just making them “disabled”) and in case they have all been selected, display a customizable “There are no more images to select” message.

This message could be simply hidden using css:

```html
<div class="selectable-images">
	<div class="isi-thumb selected"><!-- Thumb’s markup --></div>
	<div class="isi-message">There are no more images to select</div>
</div>
```

```css
.isi-message {
	margin: 0 10px 10px 0;
	color: white;
}
.isi-thumb.selected,
.isi-thumb:not(.selected) ~ .isi-message {
	display: none;
}
```

<img width="1118" alt="Screenshot 2024-11-13 at 14 39 25" src="https://github.com/user-attachments/assets/20b7a46d-e658-4e44-a261-cf207ce4c1dc">

**Comment by Toutouwai** [comment]
I don't want to change the module itself because I don't like the idea of the thumbnail layout changing as images are selected. What I mean is, if you can see three or four thumbnails that you want to select it becomes harder to select them when they are jumping around after each selection click.

But if you have a project where you prefer it that way you can achieve it with some custom CSS.

```css
.InputfieldSelectImages {
    .selectable-images {
        .isi-thumb.selected { display:none; }
        &:not(:has(.isi-thumb:not(.selected)))::after { content:'There are no more images to select.'; color:white; width:100%; padding-bottom:10px; }
    }
}
```
